version: "3.9"

services:
  database_clinic:
    image: postgres
    container_name: database_clinic
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clinic
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: clinic
    ports: 
      - 9999:9999
    volumes:
      - .:/usr/app
    links:
      - database_clinic
    depends_on:
      - database_clinic

volumes:
  pgdata:
    driver: local